/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.dashboard;

import backend.connections.DatabaseConnections;
import backend.controllers.UserController;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;



/**
 *
 * @author DELL
 */
public class Dashboard extends javax.swing.JPanel {


    private int userId;
    private long accountNumber;
    
    public Dashboard() {
    initComponents();
    loadUserData(); 
}
    
    private void loadUserData() {
    int userId = UserController.getUserId();
    try (Connection conn = DatabaseConnections.getConnection()) {
        if (conn == null) return;

        String userSql = "SELECT name FROM users WHERE user_id = ?";
        try (PreparedStatement stmt = conn.prepareStatement(userSql)) {
            stmt.setInt(1, userId);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                name.setText("<html>Name : <br><br><br>" + rs.getString("name") + "</html>");
            }
        }

        String accountSql = "SELECT account_number, account_type FROM accounts WHERE user_id = ? LIMIT 1";
        try (PreparedStatement stmt = conn.prepareStatement(accountSql)) {
            stmt.setInt(1, userId);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                AccNum.setText("<html>Account Number : <br><br><br>" + rs.getLong("account_number") + "</html>");
                AccountType.setText("<html>Account Type : <br><br><br>" + rs.getString("account_type") + "</html>");
            }
        }

        String transSql = "SELECT transaction_type, amount, transaction_date FROM transactions " +
                         "WHERE user_id = ? ORDER BY transaction_date DESC LIMIT 1";
        try (PreparedStatement stmt = conn.prepareStatement(transSql)) {
            stmt.setInt(1, userId);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                String lastTrans = String.format("%s: $%.2f on %s",
                    rs.getString("transaction_type"),
                    rs.getDouble("amount"),
                    rs.getTimestamp("transaction_date"));
                LastTransaction.setText("<html>Last Transaction : <br><br><br>" + lastTrans + "</html>");
            } else {
                LastTransaction.setText("<html>Last Transaction : <br><br><br>None</html>");
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}


    public void updateUserInfo(String userName, String accountType, long accountNumber, String lastTransaction) {
    Font labelFont = new Font("Arial", Font.BOLD, 14);
    Font valueFont = new Font("Arial", Font.PLAIN, 14);
    name.setText("<html>Name : <br><br><br>" + userName + "</html>");
    AccountType.setText("<html>Account Type : <br><br><br>" + accountType + "</html>");
    AccNum.setText("<html>Account Number : <br><br><br>" + accountNumber + "</html>");
    LastTransaction.setText("<html>Last Transaction : <br><br><br>" + lastTransaction + "</html>");
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Go2Dash = new javax.swing.JButton();
        Go2Account = new javax.swing.JButton();
        Go2Trans = new javax.swing.JButton();
        AccountType = new javax.swing.JLabel();
        LastTransaction = new javax.swing.JLabel();
        AccNum = new javax.swing.JLabel();
        name = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(240, 236, 229));

        jPanel2.setBackground(new java.awt.Color(22, 26, 48));

        Go2Dash.setBackground(new java.awt.Color(96, 114, 116));
        Go2Dash.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Go2Dash.setForeground(new java.awt.Color(255, 255, 255));
        Go2Dash.setText("Dashboard");

        Go2Account.setBackground(new java.awt.Color(96, 114, 116));
        Go2Account.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Go2Account.setForeground(new java.awt.Color(255, 255, 255));
        Go2Account.setText("Account");
        Go2Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go2AccountActionPerformed(evt);
            }
        });

        Go2Trans.setBackground(new java.awt.Color(96, 114, 116));
        Go2Trans.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Go2Trans.setForeground(new java.awt.Color(255, 255, 255));
        Go2Trans.setText("Transactions");
        Go2Trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go2TransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Go2Trans, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Go2Account, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Go2Dash, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(Go2Dash, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Go2Trans, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(Go2Account, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        AccountType.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        AccountType.setText("Account Type");

        LastTransaction.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LastTransaction.setText("Last Transaction");

        AccNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AccNum.setText("Account number ");

        name.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        name.setText("name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LastTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(AccNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(169, 169, 169))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Go2TransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go2TransActionPerformed
        transactions transactionsPanel = new transactions();
        
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        
        mainFrame.getContentPane().removeAll();
        mainFrame.getContentPane().add(transactionsPanel);
        
        mainFrame.revalidate();
        mainFrame.repaint();
        
    }//GEN-LAST:event_Go2TransActionPerformed

    private void Go2AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go2AccountActionPerformed
        account accountPanel = new account();
        
        JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        
        mainFrame.getContentPane().removeAll();
        mainFrame.getContentPane().add(accountPanel);
        
        mainFrame.revalidate();
        mainFrame.repaint();
        
        
    }//GEN-LAST:event_Go2AccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccNum;
    private javax.swing.JLabel AccountType;
    private javax.swing.JButton Go2Account;
    private javax.swing.JButton Go2Dash;
    private javax.swing.JButton Go2Trans;
    private javax.swing.JLabel LastTransaction;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
