/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend.dashboard;

import javax.swing.JFrame;
import backend.connections.DatabaseConnections;
import java.math.BigDecimal;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import backend.controllers.UserController;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class transactions extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public transactions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Go2Dash = new javax.swing.JButton();
        Go2Account = new javax.swing.JButton();
        Go2Trans = new javax.swing.JButton();
        CheckBalnced = new javax.swing.JButton();
        Withdraw = new javax.swing.JButton();
        TransactionHistory = new javax.swing.JButton();
        Deposit = new javax.swing.JButton();
        FundTransfer = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(240, 236, 229));

        jPanel2.setBackground(new java.awt.Color(22, 26, 48));

        Go2Dash.setBackground(new java.awt.Color(96, 114, 116));
        Go2Dash.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Go2Dash.setForeground(new java.awt.Color(255, 255, 255));
        Go2Dash.setText("Dashboard");
        Go2Dash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go2DashActionPerformed(evt);
            }
        });

        Go2Account.setBackground(new java.awt.Color(96, 114, 116));
        Go2Account.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Go2Account.setForeground(new java.awt.Color(255, 255, 255));
        Go2Account.setText("Account");
        Go2Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go2AccountActionPerformed(evt);
            }
        });

        Go2Trans.setBackground(new java.awt.Color(96, 114, 116));
        Go2Trans.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Go2Trans.setForeground(new java.awt.Color(255, 255, 255));
        Go2Trans.setText("Transactions");
        Go2Trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go2TransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Go2Trans, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Go2Account, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Go2Dash, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(Go2Dash, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(Go2Trans, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Go2Account, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CheckBalnced.setBackground(new java.awt.Color(163, 154, 140));
        CheckBalnced.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CheckBalnced.setForeground(new java.awt.Color(255, 255, 255));
        CheckBalnced.setText("Check balnced");
        CheckBalnced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBalncedActionPerformed(evt);
            }
        });

        Withdraw.setBackground(new java.awt.Color(163, 154, 140));
        Withdraw.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Withdraw.setForeground(new java.awt.Color(255, 255, 255));
        Withdraw.setText("Withdraw");
        Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawActionPerformed(evt);
            }
        });

        TransactionHistory.setBackground(new java.awt.Color(163, 154, 140));
        TransactionHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TransactionHistory.setForeground(new java.awt.Color(255, 255, 255));
        TransactionHistory.setText("Transaction history");
        TransactionHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionHistoryActionPerformed(evt);
            }
        });

        Deposit.setBackground(new java.awt.Color(163, 154, 140));
        Deposit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Deposit.setForeground(new java.awt.Color(255, 255, 255));
        Deposit.setText("Deposit");
        Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositActionPerformed(evt);
            }
        });

        FundTransfer.setBackground(new java.awt.Color(163, 154, 140));
        FundTransfer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FundTransfer.setForeground(new java.awt.Color(255, 255, 255));
        FundTransfer.setText("Fund transfer");
        FundTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FundTransferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TransactionHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBalnced, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Deposit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FundTransfer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBalnced, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FundTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(TransactionHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Go2TransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go2TransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Go2TransActionPerformed

    private void CheckBalncedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBalncedActionPerformed

        try {
        int userId = UserController.getUserId();
        String sql = "SELECT balance FROM accounts WHERE user_id = ?";
        
        try (Connection conn = DatabaseConnections.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, userId);
            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
                double balance = rs.getDouble("balance");
                JOptionPane.showMessageDialog(this, 
                    "Your balance: $" + balance,
                    "Account Balance", 
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, 
                    "No account found",
                    "Error", 
                    JOptionPane.WARNING_MESSAGE);
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error checking balance",
            "Database Error", 
            JOptionPane.ERROR_MESSAGE);
    }
        
        
    }//GEN-LAST:event_CheckBalncedActionPerformed

    private void WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawActionPerformed
    Withdraw withdrawPanel = new Withdraw();

    JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    mainFrame.getContentPane().removeAll();
    mainFrame.getContentPane().add(withdrawPanel);

    mainFrame.pack();
    mainFrame.revalidate();
    mainFrame.repaint();

    mainFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_WithdrawActionPerformed

    private void TransactionHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionHistoryActionPerformed
        DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Date");
    model.addColumn("Type");
    model.addColumn("From Account");
    model.addColumn("To Account");
    model.addColumn("Amount");

    try (Connection conn = DatabaseConnections.getConnection()) {
        String sql = "SELECT transaction_date, transaction_type, from_account, " +
                     "to_account, amount FROM transactions " +
                     "WHERE user_id = ? ORDER BY transaction_date DESC";
        
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1, UserController.getUserId());
        ResultSet rs = stmt.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getTimestamp("transaction_date"),
                rs.getString("transaction_type"),
                rs.getLong("from_account"),
                rs.getLong("to_account"),
                rs.getDouble("amount")
            });
        }

        JTable table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        JOptionPane.showMessageDialog(this, scrollPane, 
            "Transaction History", JOptionPane.PLAIN_MESSAGE);

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading transactions: " + e.getMessage());
    }
    }//GEN-LAST:event_TransactionHistoryActionPerformed

    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
    Deposit depositPanel = new Deposit();

    JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

    mainFrame.getContentPane().removeAll();

    mainFrame.getContentPane().add(depositPanel);

    mainFrame.pack(); 
    mainFrame.revalidate();
    mainFrame.repaint();
    mainFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_DepositActionPerformed

    private void Go2DashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go2DashActionPerformed
    int userId = UserController.getUserId();

    Dashboard dashboardPanel = new Dashboard();
    JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    mainFrame.getContentPane().removeAll();
    mainFrame.getContentPane().add(dashboardPanel);

    mainFrame.revalidate();
    mainFrame.repaint();
    }//GEN-LAST:event_Go2DashActionPerformed

    private void Go2AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go2AccountActionPerformed
       
account accountPanel = new account();

    JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

    mainFrame.getContentPane().removeAll();
    mainFrame.getContentPane().add(accountPanel);
    mainFrame.revalidate();
    mainFrame.repaint();

    }//GEN-LAST:event_Go2AccountActionPerformed

    private void FundTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FundTransferActionPerformed

    FundTransfer fundTransferPanel = new FundTransfer();

    JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

    mainFrame.getContentPane().removeAll();

    mainFrame.getContentPane().add(fundTransferPanel);
    mainFrame.pack();

    mainFrame.revalidate();
    mainFrame.repaint();
    mainFrame.setLocationRelativeTo(null);  
        
        
    }//GEN-LAST:event_FundTransferActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckBalnced;
    private javax.swing.JButton Deposit;
    private javax.swing.JButton FundTransfer;
    private javax.swing.JButton Go2Account;
    private javax.swing.JButton Go2Dash;
    private javax.swing.JButton Go2Trans;
    private javax.swing.JButton TransactionHistory;
    private javax.swing.JButton Withdraw;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
